---
 - hosts: localhost
   connection: local
   become: true

   tasks:
   - name: install htop, mc, cmatrix, nvim, tmux
     package:
       name:
       - htop
       - mc
       - cmatrix
       - nvim
       - tmux
