---
 - hosts: localhost
   connection: local
   become: true

   tasks:
   - name: install htop, mc, cmatrix, neovim, tmux
     package:
       name:
       - htop
       - mc
       - cmatrix
       - neovim
       - tmux
